export const MARKER_CLICK = 'marker_click';
export const MARKER_OVER= 'marker_over';
export const MARKER_OUT = 'marker_out';
export const FETCH_LOCATIONS = 'fetch_locations';
export const CATEGORY_CHANGE = 'category_change';
export const MAP_MOVED = 'map_moved';
export const GET_CITY = 'get_city';
export const LOCATION_CHANGE = 'zipcode_changed';
export const LATLNG_CHANGE = 'latlng_changed'
